services:
  postgres:
    image: postgres:latest
    container_name: payment-postgres
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - payment_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment -d payment_db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  payment_pg_data: